services:
  mongo:
    image: mongo:6
    container_name: todos-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./ToDOsBE
    container_name: ToDos-backend
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/todosdb
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./ToDOsFE
    container_name: ToDos-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mongo_data:

